import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    'introduction',
    'quickstart',
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      'items': [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'link',
      label: 'Configuration',
      href: 'https://docs.rs/slatedb/latest/slatedb/config/index.html',
    },
    'architecture',
    {
      type: 'link',
      label: 'Design Documents',
      href: 'https://github.com/slatedb/slatedb/tree/main/rfcs',
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      'items': [
        {
          type: 'autogenerated',
          dirName: 'operations',
        },
      ],
    },
    'faq',
    {
      type: 'link',
      label: 'API Reference',
      href: 'https://docs.rs/slatedb',
    },
  ],
};

export default sidebars;
